services:
    mmi.security.auth:
        class: Mmi\Security\Auth
        arguments:
            - '@mmi.session.session_space'

    mmi.security.acl:
        class: Mmi\Security\Acl
    
    mmi.security.handler.apc:
        class: Mmi\Session\ApcHandler
        tags:
            - { name: "cms.session.handler" }
    
    mmi.security.handler.file:
        class: Mmi\Session\FileHandler
        tags:
            - "cms.session.handler"

