services:
    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false
        
    Mmi\Security\Auth: ~
    Mmi\Security\Acl: ~
    
    Mmi\Session\SessionSpace:
        arguments:
            - 'Auth'
            
    Mmi\Session\ApcHandler:
        tags:
            - "cms.session.handler"
    
    Mmi\Session\FileHandler:
        tags:
            - "cms.session.handler"

    Mmi\Session\Session: ~
