services:
    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false

    Mmi\EventListener\KernelRequestSessionWarmer:
        tags:
            - { name: "kernel.event_subscriber", event: "kernel.request", method: "warmUpSession" }
