services:
    mmi.orm.db_connector:
        class: Mmi\Orm\DbConnector
        arguments:
            - '@mmi.orm.adapter.default'
            - '@mmi.orm.cache.default'

    mmi.orm.convert:
        class: Mmi\Orm\Convert

    mmi.orm.builder:
        class: Mmi\Orm\Builder
        arguments:
            - '@mmi.orm.db_connector'
            - '@mmi.orm.convert'
        
    mmi.session.handler.db_handler:
        class: Mmi\Session\DbHandler
        tags:
            - "cms.session.handler"
