name: "Code analysis and tests"
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: mycache
    - run: nix-build
    - run: nix-shell --run "composer test:security-checker"
    - run: nix-shell --run "composer test:phpcs"
    - run: nix-shell --run "composer test:phpstan"
    - run: nix-shell --run "composer test:phpmd"
    - run: nix-shell --run "composer test:unit"