name: "Code analysis and tests"
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v18
    - run: nix-build
    - run: nix-shell --run "composer test:all"