name: "Code analysis and checks"

on:

  pull_request:
  push:
    
jobs:

  build-images:
    strategy:
      matrix:
        version: ['8.1', '8.2']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: mmi-php${{ matrix.version }}:latest
        outputs: type=docker,dest=/tmp/mmi-php${{ matrix.version }}.tar
        build-args: PHP_VERSION=${{ matrix.version }}

  phpUnit:
    needs: build-images
    strategy:
      matrix:
        version: ['8.1', '8.2']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Download image
      uses: actions/download-artifact@v3
      with:
        name: mmi-php${{ matrix.version }}
        path: /tmp
    - name: Run PHPUnit
      run: |
        docker load --input /tmp/mmi-php${{ matrix.version }}
        docker run mmi-php${{ matrix.version }}:latest composer test:all

  PHPMD:
    needs: build-images
    strategy:
      matrix:
        version: ['8.1', '8.2']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Download image
      uses: actions/download-artifact@v3
      with:
        name: mmi-php${{ matrix.version }}
        path: /tmp
    - name: Run PHPUnit
      run: |
        docker load --input /tmp/mmi-php${{ matrix.version }}
        docker run mmi-php${{ matrix.version }}:latest composer test:phpmd